[package]
name = "pfx"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
environmental = { workspace = true }
glob = { workspace = true }
hex = { workspace = true, features = ["alloc"] }
hex_fmt = { workspace = true }
hex-literal = { workspace = true }
h2 = { workspace = true }
im = { workspace = true }
itertools = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
num-bigint = { workspace = true }
once_cell = { workspace = true }
parity-scale-codec = { workspace = true, features = [
    "derive",
    "full",
    "chain-error",
] }
parking_lot = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
ring = { workspace = true }
scale-info = { workspace = true, features = ["derive"] }
scopeguard = { workspace = true }
serde = { workspace = true, features = ["derive", "std", "rc"] }
serde_cbor = { workspace = true }
serde_json = { workspace = true }
sp-externalities = { workspace = true }
sp-io = { workspace = true, features = [
    "disable_panic_handler",
    "disable_oom",
] } #, "disable_allocator"] }
sp-runtime = { workspace = true }
sp-state-machine = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-stream = { workspace = true }
tracing = { workspace = true }
# for light_validation
derive_more = { workspace = true, features = ["from", "deref", "deref_mut"] }
finality-grandpa = { workspace = true, features = ["derive-codec"] }
frame-system = { workspace = true }
hash-db = { workspace = true }
num-traits = { workspace = true }
sp-application-crypto = { workspace = true }
sp-consensus-grandpa = { workspace = true }
sp-core = { workspace = true }
sp-trie = { workspace = true }
tonic = { workspace = true }
rsa = { workspace = true }

# PFLX specific
pfx-crypto = { workspace = true, features = [
    "stream",
    "full_crypto",
] }
pfx-mq = { workspace = true, features = [
    "dispatcher",
    "queue",
    "checkpoint",
    "signers",
] }
pfx-pallet-mq = { workspace = true }
pfx-serde-more = { workspace = true }
pfx-trie-storage = { workspace = true }
pfx-types = { workspace = true, features = ["enable_serde", "full_crypto"] }
pfx-api = { workspace = true }
pfx-pal = { workspace = true }
pfx-pallet-tee-worker = { workspace = true }
reqwest-env-proxy = { workspace = true }
runtime = { workspace = true, features = ["std"] }
sgx-api-lite = { workspace = true }

dashmap = { workspace = true }
prost = { workspace = true, features = ["std"] }
rust-crypto = { workspace = true }
num-bigint-dig = { workspace = true }


[dev-dependencies]
insta = "1.7.2"
rmp-serde = "1"
serde_path_to_error = "0.1.5"
ron = "0.8.0"
ciborium = "0.2.0"

[features]
default = ["sp-io/disable_panic_handler", "sp-io/disable_oom"]
shadow-gk = []

only-attestation = [
	"runtime/only-attestation"
]
verify-pflixbin = [
	"runtime/verify-pflixbin"
]